#!/usr/bin/env python
import base64
import json
import sys
from collections import OrderedDict

import bencode

s = b''
s += sys.stdin.buffer.read()
b = (bencode.decode(s))


def parse(v):
    if type(v) == bytes:
        return base64.b64encode(v, b'+-').decode('utf-8')
    elif type(v) == list:
        return [parse(i) for i in v]
    elif type(v) == dict or type(v) == OrderedDict:
        return {k: parse(i) for k, i in v.items()}
    else:
        return v


print(json.dumps(parse(b)))
