NODE_ID_BYTE_SIZE = 32
DROP_ID_BYTE_SIZE = 64

TYPE_INDEX = 0
ID_INDEX = 1
VALUE_INDEX = 2

DROP_NODE_INDEX = 0
DROP_IP_INDEX = 1
DROP_PORT_INDEX = 2
DROP_TIMESTAMP_INDEX = 3

OK_RESULT = 'OK'
ERROR_RESULT = 'ERROR'
